import get from "lodash.get";
import map from "lodash.map";
import foreach from "lodash.foreach";
import filter from "lodash.filter";
import reduce from "lodash.reduce";
import find from "lodash.find";
import findindex from "lodash.findindex";
import isnil from "lodash.isnil";
import split from "lodash.split";
import deburr from "lodash.deburr";
import debounce from "lodash.debounce";
import toupper from "lodash.toupper";
import upperfirst from "lodash.upperfirst";
import tolower from "lodash.tolower";
import trim from "lodash.trim";
import flattendeep from "lodash.flattendeep";
import fill from "lodash.fill";

export const lodashGet = get;
export const lodashMap = map;
export const lodashForEach = foreach;
export const lodashFilter = filter;
export const lodashReduce = reduce;
export const lodashFind = find;
export const lodashFindIndex = findindex;
export const lodashIsNil = isnil;
export const lodashSplit = split;
export const lodashDeburr = deburr;
export const lodashDebounce = debounce;
export const lodashToUpper = toupper;
export const lodashUpperFirst = upperfirst;
export const lodashToLower = tolower;
export const lodashTrim = trim;
export const lodashFlattenDeep = flattendeep;
export const lodashFill = fill;
