const createAttributeListValuesModel = require("../models/attribute_list_values.model");

const attributeGroups = require("./attribute_groups/attribute_groups.service.js");
const attributes = require("./attributes/attributes.service.js");
const colors = require("./colors/colors.service.js");
const companyStatuses = require("./company_statuses/company_statuses.service.js");
const companies = require("./companies/companies.service.js");
const configs = require("./configs/configs.service.js");
const machineAttributes = require("./machine_attributes/machine_attributes.service.js");
const machineMoldProducts = require("./machine_mold_products/machine_mold_products.service.js");
const machineStatuses = require("./machine_statuses/machine_statuses.service.js");
const machineTypes = require("./machine_types/machine_types.service.js");
const machines = require("./machines/machines.service.js");
const measurementUnits = require("./measurement_units/measurement_units.service.js");
const moldAttributes = require("./mold_attributes/mold_attributes.service.js");
const moldProducts = require("./mold_products/mold_products.service.js");
const moldStatuses = require("./mold_statuses/mold_statuses.service.js");
const molds = require("./molds/molds.service.js");
const notifications = require("./notifications/notifications.service.js");
const nozzleTypes = require("./nozzle_types/nozzle_types.service.js");
const plantStatuses = require("./plant_statuses/plant_statuses.service.js");
const plants = require("./plants/plants.service.js");
const productionOrderActionTypes = require("./production_order_action_types/production_order_action_types.service.js");
const productionOrderEventTypes = require("./production_order_event_types/production_order_event_types.service.js");
const productionOrderEvents = require("./production_order_events/production_order_events.service.js");
const productionOrderHistory = require("./production_order_history/production_order_history.service.js");
const productionOrderWaste = require("./production_order_waste/production_order_waste.service.js");
const productionOrderStatuses = require("./production_order_statuses/production_order_statuses.service.js");
const productionOrderTypes = require("./production_order_types/production_order_types.service.js");
const productionOrders = require("./production_orders/production_orders.service.js");
const productAttributes = require("./product_attributes/product_attributes.service.js");
const productMatTypes = require("./product_mat_types/product_mat_types.service.js");
const productStatuses = require("./product_statuses/product_statuses.service.js");
const products = require("./products/products.service.js");
const sensorAttributes = require("./sensor_attributes/sensor_attributes.service.js");
const sensorStatuses = require("./sensor_statuses/sensor_statuses.service.js");
const sensors = require("./sensors/sensors.service.js");
const siteContacts = require("./site_contacts/site_contacts.service.js");
const roles = require("./roles/roles.service.js");
const roleStatuses = require("./role_statuses/role_statuses.service.js");
const userRoles = require("./user_roles/user_roles.service.js");
const users = require("./users/users.service.js");
const userStatuses = require("./user_statuses/user_statuses.service.js");
const turns = require("./turns/turns.service.js");
const holidays = require("./holidays/holidays.service.js");
const wasteJustifications = require("./waste_justifications/waste_justifications.service.js");
const wikiPages = require("./wiki_pages/wiki_pages.service.js");
const wikiSections = require("./wiki_sections/wiki_sections.service.js");
const tickets = require("./support/tickets/tickets.service.js");
const ticket_messages = require("./support/ticket_messages/ticket_messages.service.js");
const ticket_statuses = require("./support/ticket_statuses/ticket_statuses.service.js");
const simpleAccounts = require("./simple_accounts/simple_accounts.service.js");
const simpleAccountsStatus = require("./simple_accounts_status/simple_accounts_status.service.js");
const simpleAccountRoles = require("./simple_account_roles/simple_account_roles.service.js");

module.exports = function (app) {
  createAttributeListValuesModel(app);
  app.configure(attributeGroups);
  app.configure(attributes);
  app.configure(colors);
  app.configure(companyStatuses);
  app.configure(companies);
  app.configure(configs);
  app.configure(machineAttributes);
  app.configure(machineMoldProducts);
  app.configure(machineStatuses);
  app.configure(machineTypes);
  app.configure(machines);
  app.configure(measurementUnits);
  app.configure(moldAttributes);
  app.configure(moldProducts);
  app.configure(moldStatuses);
  app.configure(molds);
  app.configure(notifications);
  app.configure(nozzleTypes);
  app.configure(plantStatuses);
  app.configure(plants);
  app.configure(productionOrderActionTypes);
  app.configure(productionOrderEventTypes);
  app.configure(productionOrderEvents);
  app.configure(productionOrderHistory);
  app.configure(productionOrderWaste);
  app.configure(productionOrderStatuses);
  app.configure(productionOrderTypes);
  app.configure(productionOrders);
  app.configure(productAttributes);
  app.configure(productMatTypes);
  app.configure(productStatuses);
  app.configure(products);
  app.configure(sensorAttributes);
  app.configure(sensorStatuses);
  app.configure(sensors);
  app.configure(siteContacts);
  app.configure(roleStatuses);
  app.configure(roles);
  app.configure(userRoles);
  app.configure(userStatuses);
  app.configure(users);
  app.configure(turns);
  app.configure(holidays);
  app.configure(wasteJustifications);
  app.configure(wikiPages);
  app.configure(wikiSections);
  app.configure(tickets);
  app.configure(ticket_messages);
  app.configure(ticket_statuses);
  app.configure(simpleAccounts);
  app.configure(simpleAccountsStatus);
  app.configure(simpleAccountRoles);
};
