import eCompaniesModel from "./companies/model";
import eSensorsModel from "./sensors/model";
import eColorsModel from "./colors/model";
import eMeasurementUnitsModel from "./measurement-units/model";
import ePlantStatusesModel from "./plant-statuses/model";
import eProductionOrderStatusesModel from "./production-order-statuses/model";
import eProductionOrderActionTypesModel from "./production-order-action-types/model";
import eCompanyStatusesModel from "./company-statuses/model";
import eMachineStatusesModel from "./machine-statuses/model";
import eMoldStatusesModel from "./mold-statuses/model";
import eProductStatusesModel from "./product-statuses/model";
import eSensorStatusesModel from "./sensor-statuses/model";
import eRolesModel from "./roles/model";
import eRoleStatusesModel from "./role-statuses/model";
import eUserStatusesModel from "./user-statuses/model";
import eTicketStatusesModel from "./ticket-statuses/model";

export const CompaniesModel = eCompaniesModel;
export const SensorsModel = eSensorsModel;
export const ColorsModel = eColorsModel;
export const MeasurementUnitsModel = eMeasurementUnitsModel;
export const PlantStatusesModel = ePlantStatusesModel;
export const ProductionOrderStatusesModel = eProductionOrderStatusesModel;
export const ProductionOrderActionTypesModel = eProductionOrderActionTypesModel;
export const CompanyStatusesModel = eCompanyStatusesModel;
export const MachineStatusesModel = eMachineStatusesModel;
export const MoldStatusesModel = eMoldStatusesModel;
export const ProductStatusesModel = eProductStatusesModel;
export const SensorStatusesModel = eSensorStatusesModel;
export const RolesModel = eRolesModel;
export const RoleStatusesModel = eRoleStatusesModel;
export const UserStatusesModel = eUserStatusesModel;
export const TicketStatusesModel = eTicketStatusesModel;
