import eShell from "./layout/Shell";
import eClientRoute from "./routes/ClientRoute";
import eAdminRoute from "./routes/AdminRoute";
import eSessionRoute from "./routes/SessionRoute";
import eWithMasterDataListPage from "./pages/withMasterDataList";
import eWithMasterDataFormPage from "./pages/withMasterDataForm";
import eWithAdministrationPage from "./pages/withAdministrationPage";
import eMasterDataCard from "./master-data-card";
import eMasterDataForm from "./master-data-form";
import ePlantTurnsTable from "./plant-turns-table";
import ePlantHolidaysTable from "./plant-holidays-table";
import eMoldProductsTable from "./mold-products-table";
import eMachineMoldProductsTable from "./machine-mold-products-table";
import eWikiPageWikiSectionsTable from "./wiki-page-wiki-sections-table";
import eBreadCrumbs from "./breadcrumbs";
import eFormInput from "./master-data-form/FormInput";
import eFieldsRow from "./master-data-form/FieldsRow";
import eTree from "./master-data-form/Tree";
import eLoader from "./loader";
import eErrors from "./errors";
import eNotFound from "./not-found";
import eButton from "./buttons";
import eChatSupport from './chat-support';

export const Shell = eShell;
export const ClientRoute = eClientRoute;
export const AdminRoute = eAdminRoute;
export const SessionRoute = eSessionRoute;
export const withMasterDataListPage = eWithMasterDataListPage;
export const withMasterDataFormPage = eWithMasterDataFormPage;
export const withAdministrationPage = eWithAdministrationPage;
export const MasterDataCard = eMasterDataCard;
export const MasterDataForm = eMasterDataForm;
export const PlantTurnsTable = ePlantTurnsTable;
export const PlantHolidaysTable = ePlantHolidaysTable;
export const MoldProductsTable = eMoldProductsTable;
export const MachineMoldProductsTable = eMachineMoldProductsTable;
export const WikiPageWikiSectionsTable = eWikiPageWikiSectionsTable;
export const FormInput = eFormInput;
export const FieldsRow = eFieldsRow;
export const Tree = eTree;
export const BreadCrumbs = eBreadCrumbs;
export const Loader = eLoader;
export const Errors = eErrors;
export const NotFound = eNotFound;
export const Button = eButton;
export const ChatSupport = eChatSupport;
